language: node_js
node_js:
- 10.13.0

branches:
  only:
  - master

deploy:
  provider: heroku
  skip_cleanup: true
  keep-history: true
  app: backend-coding-test
  api_key:
    secure: $HEROKU_API_KEY
