language: node_js
node_js:
- 10.13.0
deploy:
  provider: heroku
  api_key:
    secure: XPs5Hx74Pac18nnLGxkISo+iiCzwGbKOVB+HWvIl8Y3MVABGQF6fIWmRBeNrA8FPrr5DKnGCgc2uVTMnPEPDvlM6Bu67j6mSnQeSktXod/odj9KSKrvIpdzgtf5VwSICCxpl054xHT9kIPQsjX2xJW1A7rz87QYUH/q7vHKrtvz5rbvkR/tGVRNvSh6ZZYNhToh5Tt0cE9Ghm6gcVHhSm1j7/PWJ9MQr13AdWO84+J1ppZ0k+W18bEYtnkTQkWEKwx5E3SRUTB+Zb3j1pZPL3dBL2abWdin88Hj2MEBeDKow5fvqMiApqJcRW1DOwhEGI7Yp/Oz6Ps8CS9SATQgbtu1kVB8vXcWH7zmBnNVs6pULvQqmU5Qku62yAj+54E5M3JLD3l0G2V9btGDtM0GYvrsL6Ie4N3ZwKHWQoFuL8qMChbF2mJc6sM6rlwpQTwZ8nrvTwyMr9p4hxQ69kOE8JeQkzqxrgF9R4dfyqqM12oCx0NAqDCoYWhGm0gQgaik3QLKkMLAag3WI018LoIMDp98yGkNYuFRUcfJ8IAi9M6Y8deoCBAyrVBvWyM3Bn2I+oyC+0Fm8b/++bxq8JhqesCYW8mjljr1otn9I+mQS15KjpXQ9XAeE8ZU24D/Ytbb6Zsi4VGMTq774ZCN5hj1Anh+q9hqGaVZMbv99aq4wWBc=
