language: node_js
node_js:
- 10.13.0
branches:
  only:
  - master
deploy:
  provider: heroku
  skip_cleanup: true
  keep-history: true
  app: backend-coding-test
  api_key:
    secure: lOl74g0c/DKY0NF5w8KfWuvnIBnXZw0oy/HsWz3mQAWx+7xdpBw+NuXHsyvk7YcaMY6BNPl+hQt9lngtFJfHvEEoyoa3hVLAevIbHn0lxdBC+f6nBESq6k9bacNhEYGcJTWQfQjIqRB4JSewzPL+IwgOZGmdq3MHXISgY9CC33caJcf05dR6ohT64tJ0+LXLRSys3YHUpZyHrXBCvGWp1ItOa1rGOCagXEeuU/ZUKR7TVRo2vj9o+S+thnBaGlGPH8f7kRUO2NgAmkG8s47OrmSrNetU7sP2dbDUIB+8ugTrCN1B9kN6cQCrnyQWG05QGrF4xJfHWXNkromVK2NI3vODrGswGImfsKev9oDX0DirnYUUAWzCRfEzMHpgylMZcaDrZT6+sljiSsMMRI7AufzvQoDKD/2Aw6CBMlc7fh+qFrS9CFzMEcWIkeKD2WH3eu1csRQeunmqBhBS6gLcaE+cUM9mnextXi6C8LQzCBFNgLUZmWXXg1SGJGAn053h919A357KKIJm41NCA2YaABT+QhEQKOwRdogNzn2e1bz1n0shKjY8/dPsr2A1meuCcfXI9XVS/Eprc5uJKKsDAH5BN4NDG8BEJGM3zdcvk1+elEvJHIeiLjJ70O0/T0ytudFirkOOEWbxwutAgpryiykNYsfJeF1wKa+wyWWJLXY=
